name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Setup Gradle Wrapper
      run: |
        if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
          echo "Gradle wrapper not found, downloading..."
          mkdir -p gradle/wrapper
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v8.0.2/gradle/wrapper/gradle-wrapper.jar
        fi

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean project
      run: ./gradlew clean --no-daemon --stacktrace

    - name: Build debug APK
      run: ./gradlew assembleDebug --no-daemon --stacktrace
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: personalia-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Personalia App v1.0.${{ github.run_number }}
        body: |
          🎉 **Aplikasi Personalia Sekolah**
          
          📱 **Fitur:**
          - ✅ Manajemen data Staff (5 kategori)
          - ✅ Manajemen data Siswa (10 kelas)
          - ✅ CRUD operations lengkap
          - ✅ Search & filter data
          - ✅ Data persistent (JSON storage)
          - ✅ Material Design 3 UI
          
          📥 **Cara Install:**
          1. Download file `app-debug.apk`
          2. Enable "Install from Unknown Sources" di Android
          3. Install APK
          4. Buka aplikasi "Personalia"
          
          🔧 **Requirements:**
          - Android 5.1+ (API 22+)
          - 50MB storage space
          
          📊 **Build Info:**
          - Build: #${{ github.run_number }}
          - Commit: ${{ github.sha }}
          - Date: ${{ github.event.head_commit.timestamp }}
        files: |
          app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
